#!/usr/bin/python3


# The Invoice Management System

# 	This is the head-script. It cares about all
#	global tasks, which are
#
#	- init a new repo
#	- manage the command line options
#	- logging
#	- enviroment stuff


# Imports {{{
import os, getopt, sys
from init import init
from output import printhelp 
from output import mprint 
# }}}


# grab the current workin dir
cwd = os.getcwd()

fname = "main"
argc = len(sys.argv)

# Parse the arguments

try:
	opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
except getopt.GetoptError as err:
# print help information and exit:
	print(err) # will print something like "option -a not recognized"
	sys.exit(2)
output = None
verbose = False
for o, a in opts:
	if o in ("-h","--help"):
		printhelp()
		sys.exit(0)
	else:
		print("Undefined Arg or Option: "+ o)
		sys.exit(2)

for i in args:
	if i == "init":
		init()
		sys.exit(0)
	if i == "create":
		create()
		sys.exit(0)
	else:
		mprint(fname,1,"Invalid Action. Exiting ...")
		sys.exit(2)


